version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: application:django
    container_name: app_container
    command: gunicorn social_book.wsgi.application --bind 0.0.0.0:8000
